config/routes.rb
Rails.application.routes.draw do
  resources :mods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mod.rb
class Mod < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mods_controller.rb
class ModsController < ApplicationController
  before_action :set_mod, only: %i[ show edit update destroy ]

  # GET /mods or /mods.json
  def index
    @mods = Mod.all
  end

  # GET /mods/1 or /mods/1.json
  def show
  end

  # GET /mods/new
  def new
    @mod = Mod.new
  end

  # GET /mods/1/edit
  def edit
  end

  # POST /mods or /mods.json
  def create
    @mod = Mod.new(mod_params)

    respond_to do |format|
      if @mod.save
        format.html { redirect_to @mod, notice: "Mod was successfully created." }
        format.json { render :show, status: :created, location: @mod }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mods/1 or /mods/1.json
  def update
    respond_to do |format|
      if @mod.update(mod_params)
        format.html { redirect_to @mod, notice: "Mod was successfully updated." }
        format.json { render :show, status: :ok, location: @mod }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mods/1 or /mods/1.json
  def destroy
    @mod.destroy
    respond_to do |format|
      format.html { redirect_to mods_url, notice: "Mod was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mod
      @mod = Mod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mod_params
      params.require(:mod).permit(:name, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minecraft</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mods/_form.html.erb
<%= form_with(model: mod) do |form| %>
  <% if mod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mod.errors.count, "error") %> prohibited this mod from being saved:</h2>

      <ul>
        <% mod.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mods/edit.html.erb
<h1>Editing Mod</h1>

<%= render 'form', mod: @mod %>

<%= link_to 'Show', @mod %> |
<%= link_to 'Back', mods_path %>

app/views/mods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mods.each do |mod| %>
      <tr>
        <td><%= mod.name %></td>
        <td><%= mod.type %></td>
        <td><%= link_to 'Show', mod %></td>
        <td><%= link_to 'Edit', edit_mod_path(mod) %></td>
        <td><%= link_to 'Destroy', mod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mod', new_mod_path %>

app/views/mods/new.html.erb
<h1>New Mod</h1>

<%= render 'form', mod: @mod %>

<%= link_to 'Back', mods_path %>

app/views/mods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mod.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @mod.type %>
</p>

<%= link_to 'Edit', edit_mod_path(@mod) %> |
<%= link_to 'Back', mods_path %>